name: Deploy JPetStore

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build WAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build WAR
        run: mvn clean package -DskipTests

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Deploy WAR to Dev
        run: mvn cargo:redeploy -Dcargo.remote.username=${{ secrets.TOMCAT_USER_DEV }} -Dcargo.remote.password=${{ secrets.TOMCAT_PASS_DEV }} -Dcargo.remote.url=${{ secrets.TOMCAT_URL_DEV }}

  deploy-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Deploy WAR to Test
        run: mvn cargo:redeploy -Dcargo.remote.username=${{ secrets.TOMCAT_USER_TEST }} -Dcargo.remote.password=${{ secrets.TOMCAT_PASS_TEST }} -Dcargo.remote.url=${{ secrets.TOMCAT_URL_TEST }}

  deploy-preprod:
    name: Deploy to Pre-Prod
    runs-on: ubuntu-latest
    needs: deploy-test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Deploy WAR to Pre-Prod
        run: mvn cargo:redeploy -Dcargo.remote.username=${{ secrets.TOMCAT_USER_PREPROD }} -Dcargo.remote.password=${{ secrets.TOMCAT_PASS_PREPROD }} -Dcargo.remote.url=${{ secrets.TOMCAT_URL_PREPROD }}

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: deploy-preprod
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Deploy WAR to Prod
        run: mvn cargo:redeploy -Dcargo.remote.username=${{ secrets.TOMCAT_USER_PROD }} -Dcargo.remote.password=${{ secrets.TOMCAT_PASS_PROD }} -Dcargo.remote.url=${{ secrets.TOMCAT_URL_PROD }}
